services:
    david63.sitelogo.listener:
        class: david63\sitelogo\event\listener
        arguments:
            - @config
            - @template
            - @user
            - %core.root_path%
        tags:
            - { name: event.listener }

    david63.sitelogo.admin.controller:
        class: david63\sitelogo\controller\admin_controller
        arguments:
            - @config
            - @request
            - @template
            - @user
            - @service_container
