version: "2"
services:
  web:
    build: ./web
    # ports:
    #     - "80:80"
    expose:
      - "80"
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d
      - ./web/assets:/usr/share/nginx/html/assets
    links:
      - php
      - db
    networks:
      - default
      - proxy

  php:
    build: ./
    expose:
      - "9000"
    volumes:
      - ./lordswar:/var/www/html
      - ./log:/var/log
    links:
      - db
    networks:
      - default

# s1:
#     build: ./
#     ports:
#       - "8080:80"
#     expose:
#       - "80"
#     volumes:
#       - ./world1:/var/www/html
#     environment:
#       - VIRTUAL_HOST=s1.lordswar.sowicm.com
#     links:
#       - db

  forum:
    build:
      context: .
      dockerfile: Dockerfile-forum
    # ports:
    #     - '8080:80'
    expose:
      - "80"
    volumes:
      - ./forum:/var/www/html
    links:
      - db
    networks:
      - default
      - proxy

  db:
    image: "mysql:latest"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=96kw9o69Q6
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default

volumes:
  mysql:

networks:
  default:
  proxy:
    external:
      name: nginxproxy_proxy

# # scp lordswar_backup_* vhbackup@backup.sowicm.com:/docker_backups/
# backup_sh
# docker-compose exec db sh -c 'exec mysqldump -uroot -p96kw9o69Q6 tribalwars_main' > tribalwars_main_`date "+%F_%H"`.sql
# docker-compose exec db sh -c 'exec mysqldump -uroot -p96kw9o69Q6 pkmhunters_world' > pkmhunters_world_`date "+%F_%H"`.sql
# 7z a lordswar_backup_`date "+%F_%H"`_`pwgen -Bsv1 8` *.sql
# rm *.sql
# mv lordswar_backup_* /root/docker_backups/
# rm lordswar_backup_*
#
