
# web:
#     build: ./
#     ports:
#         - "8081:80"
#     expose:
#         - "80"
#     volumes:
#         - ./lordswar:/var/www/html
#         - ./log:/var/log
#     environment:
#         - VIRTUAL_HOST=lordswar.cn
#     links:
#         - db

web:
    restart: always
    build: ./web
    ports:
        - '8888:80'
    expose:
        - "80"
    volumes:
        - ./web/conf.d:/etc/nginx/conf.d
    environment:
        - VIRTUAL_HOST=lordswar.cn,www.lordswar.cn,s1.lordswar.cn
    links:
        - php
        - db

php:
    restart: always
    build: ./
    expose:
        - "9000"
    volumes:
        - ./lordswar:/var/www/html
        - ./log:/var/log
    links:
        - db

forum:
    restart: always
    build: ./php5forum
    ports:
        - '9999:80'
    expose:
        - "80"
    volumes:
        - ./forum:/var/www/html
    environment:
        - VIRTUAL_HOST=forum.lordswar.cn
    links:
        - db

db:
    restart: always
    image: "mysql:latest"
    expose:
        - "3306"
    ports:
        - "33062:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=96kw9o69Q6
    volumes:
        - ./mysql:/var/lib/mysql

# # scp lordswar_backup_* vhbackup@backup.sowicm.com:/docker_backups/
# backup_sh
# docker-compose exec db sh -c 'exec mysqldump -uroot -p96kw9o69Q6 tribalwars_main' > tribalwars_main_`date "+%F_%H"`.sql
# docker-compose exec db sh -c 'exec mysqldump -uroot -p96kw9o69Q6 pkmhunters_world' > pkmhunters_world_`date "+%F_%H"`.sql
# 7z a lordswar_backup_`date "+%F_%H"`_`pwgen -Bsv1 8` *.sql
# rm *.sql
# mv lordswar_backup_* /root/docker_backups/
# rm lordswar_backup_*
#
