
# web:
#     build: ./
#     ports:
#         - "8081:80"
#     expose:
#         - "80"
#     volumes:
#         - ./lordswar:/var/www/html
#         - ./log:/var/log
#     environment:
#         - VIRTUAL_HOST=lordswar.cn
#     links:
#         - db
version: "2"
services:
  web:
    restart: always
    build: ./web
    ports:
      - '8888:80'
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=lordswar.cn,www.lordswar.cn,s1.lordswar.cn
    links:
      - php
      - db
    networks:
      - default
      - proxy

  php:
    restart: always
    build: .
    expose:
      - "9000"
    links:
      - db
    networks:
      - default

  forum:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-forum_server
    ports:
      - '9999:80'
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=forum.lordswar.cn
    links:
      - db
    networks:
      - default
      - proxy

  db:
    restart: always
    image: "mysql:latest"
    expose:
      - "3306"
    ports:
      - "33062:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=96kw9o69Q6
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default

volumes:
  mysql:

networks:
  default:
  proxy:
    external:
      name: nginxproxy_proxy

# # scp lordswar_backup_* vhbackup@backup.sowicm.com:/docker_backups/
# backup_sh
# docker-compose exec db sh -c 'exec mysqldump -uroot -p96kw9o69Q6 tribalwars_main' > tribalwars_main_`date "+%F_%H"`.sql
# docker-compose exec db sh -c 'exec mysqldump -uroot -p96kw9o69Q6 pkmhunters_world' > pkmhunters_world_`date "+%F_%H"`.sql
# 7z a lordswar_backup_`date "+%F_%H"`_`pwgen -Bsv1 8` *.sql
# rm *.sql
# mv lordswar_backup_* /root/docker_backups/
# rm lordswar_backup_*
#
