
# web:
#     build: ./
#     ports:
#         - "8081:80"
#     expose:
#         - "80"
#     volumes:
#         - ./lordswar:/var/www/html
#         - ./log:/var/log
#     environment:
#         - VIRTUAL_HOST=lordswar.cn
#     links:
#         - db

web:
    build: ./web
    # ports:
    #     - "80:80"
    expose:
        - "80"
    volumes:
        - ./web/conf.d:/etc/nginx/conf.d
        - ./web/assets:/usr/share/nginx/html/assets
    environment:
        - VIRTUAL_HOST=lordswar.local,www.lordswar.local,s1.lordswar.local
    links:
        - php
        - db

php:
    build: ./
    # ports:
    #     - "9000:9000"
    expose:
        - "9000"
    volumes:
        - ./lordswar:/var/www/html
        - ./log:/var/log
    links:
        - db

# s1:
#     build: ./
#     ports:
#         - "8080:80"
#     expose:
#         - "80"
#     volumes:
#         - ./world1:/var/www/html
#     environment:
#         - VIRTUAL_HOST=s1.lordswar.sowicm.com
#     links:
#         - db

forum:
    build: ./php5forum
    # ports:
    #     - '8080:80'
    expose:
        - "80"
    volumes:
        - ./forum:/var/www/html
    environment:
        - VIRTUAL_HOST=forum.lordswar.local
    links:
        - db

db:
    image: "mysql:latest"
    expose:
        - "3306"
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=96kw9o69Q6
    volumes:
        - ./mysql:/var/lib/mysql
