
web:
    build: ./
    ports:
        - "80:80"
    expose:
        - "80"
    volumes:
        - ./tribalwars:/var/www/html
        - ./log:/var/log
    environment:
        - VIRTUAL_HOST=lordswar.cn
    links:
        - db

# s1:
#     build: ./
#     ports:
#         - "8080:80"
#     expose:
#         - "80"
#     volumes:
#         - ./world1:/var/www/html
#     environment:
#         - VIRTUAL_HOST=s1.tribalwars.sowicm.com
#     links:
#         - db

forum:
    build: ./php5forum
    ports:
        - '8080:80'
    expose:
        - "80"
    volumes:
        - ./forum:/var/www/html
    environment:
        - VIRTUAL_HOST=forum.lordswar.cn
    links:
        - db

db:
    image: "mysql:latest"
    expose:
        - "3306"
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=96kw9o69Q6
    volumes:
        - ./mysql:/var/lib/mysql
