<?php
class vhWorldUsers extends vhModel {
	function __construct() {
		$this->table = 'users';
		$this->fields = array(
			//'id',
			'username' => '',
			'password' => '',
			'banned' => 'N',
			'villages' => 0,
			'points' => 0,
			'ennobled_by' => '',
			'ally' => -1,
			'ally_titel' => '',
			'ally_found' => 0,
			'ally_lead' => 0,
			'ally_invite' => 0,
			'ally_diplomacy' => 0,
			'ally_mass_mail' => 0,
			'rang' => 0,
			'villages_mode' => 'prod',
			'attacks' => 0,
			'new_report' => 0,
			'new_mail' => 0,
			'market_sell' => 'all',
			'market_buy' => 'all',
			'market_ratio_max' => '3',
			'killed_units_att' => 0,
			'killed_units_att_rank' => 0,
			'killed_units_def' => 0,
			'killed_units_def_rank' => 0,
			'killed_units_altogether' => 0,
			'killed_units_altogether_rank' => 0,
			'do_action' => '',
			'last_activity' => 0,
			'birthday' => '',
			'vacation_id' => -1,
			'vacation_name' => '',
			'vacation_accept' => 0,
			'b_day' => 0,
			'b_month' => 0,
			'b_year' => 0,
			'sex' => 'x',
			'home' => '',
			'image' => '',
			'personal_text' => '',
			'window_width' => 840,
			'show_toolbar' => 1,
			'dyn_menu' => 1,
			'confirm_queue' => 1,
			'map_size' => 9,
			'minimap_size' => 'm',
			'memo' => '',
			'map_reload' => '',
			'graphical_overview' => 1,
			'overview' => 'new',
			'labels' => 'yes',
			'coins' => 0,
			'snobs' => 0,
			'coinsNext' => 1,
			'protection' => 0, //24, // 0 in Mysql...
			'group' => '',
			'css' => 'stamm.css',
			'image_base' => 'graphic',
			'gfx_old' => 0,
			'knightname' => '骑士',
			'data_inregistrare' => '',
			'ip_inregistrare' => '',
			'medc' => '0',
			'premium_active' => 0,
			'premium_active_until' => 0,
			'premium_activated_at' => 0,
			'join_actions' => 'n'
			);
	}
}

?>