<?php
$cl_units = new units();
$cl_units->set_unitfactor("0.65","0.94355");

$cl_units->add_unit("Escudeiro","unit_spear");
$cl_units->set_woodprice("50");
$cl_units->set_stoneprice("30");
$cl_units->set_ironprice("10");
$cl_units->set_bhprice("1");
$cl_units->set_time("1000");
$cl_units->set_att("50","1.045");
$cl_units->set_def("100","1.045");
$cl_units->set_defcav("200","1.045");
$cl_units->set_defarcher("300","1.045");
$cl_units->set_speed("720");
$cl_units->set_booty("25");
$cl_units->set_needed(array());
$cl_units->set_recruit_in("barracks");
$cl_units->set_specials(array("barracks"=>"1"));
$cl_units->set_group("foot");
$cl_units->set_col("A");
$cl_units->set_attType("def");
$cl_units->set_description("O que seria de um cavaleiro sem o seu servo! Mas mesmo sem o seu amo, os escudeiros são um apoio muito útil. Eles são bons com cavalos e, apesar de não terem muitas armas, são perfeitamente capazes de se defender de unidade montadas.");

$cl_units->add_unit("Templário","unit_sword");
$cl_units->set_woodprice("30");
$cl_units->set_stoneprice("30");
$cl_units->set_ironprice("70");
$cl_units->set_bhprice("1");
$cl_units->set_time("1500");
$cl_units->set_att("100","1.045");
$cl_units->set_def("300","1.045");
$cl_units->set_defcav("100","1.045");
$cl_units->set_defarcher("200","1.045");
$cl_units->set_speed("900");
$cl_units->set_booty("15");
$cl_units->set_needed(array("barracks"=>"1","smith"=>"1"));
$cl_units->set_recruit_in("barracks");
$cl_units->set_specials(array());
$cl_units->set_group("foot");
$cl_units->set_col("A");
$cl_units->set_attType("def");
$cl_units->set_description("Os templários são conhecidos pelos seus escudos seguros e pelo seu inabalável código de honra. Corajosamente eles permanecem no caminho de todos os inimigos, independentemente da sua força, para proteger os seu rei e povo. São particularmente bons a defender-se contra soldados da infantaria intrusos.");

$cl_units->add_unit("Guerreiro","unit_axe");
$cl_units->set_woodprice("60");
$cl_units->set_stoneprice("30");
$cl_units->set_ironprice("40");
$cl_units->set_bhprice("1");
$cl_units->set_time("1250");
$cl_units->set_att("350","1.0455");
$cl_units->set_def("70","1.045");
$cl_units->set_defcav("50","1.045");
$cl_units->set_defarcher("50","1.045");
$cl_units->set_speed("720");
$cl_units->set_booty("10");
$cl_units->set_needed(array("barracks"=>"1","smith"=>"2"));
$cl_units->set_recruit_in("barracks");
$cl_units->set_specials(array());
$cl_units->set_group("foot");
$cl_units->set_col("A");
$cl_units->set_attType("off");
$cl_units->set_description("Os guerreiros gritam o seu grito de guerra através do campo de batalha intimidando todos à sua volta, antes de se lançarem aos seus inimigos balançando os seus machados ousadamente. Uma vez soltos, não há nada que os pare e o seu desejo de ataque os fazem uma das unidades mais temidas em redor.");

if($config['archers']){
	$cl_units->add_unit("Arqueiro","unit_archer");
	$cl_units->set_woodprice("100");
	$cl_units->set_stoneprice("30");
	$cl_units->set_ironprice("60");
	$cl_units->set_bhprice("1");
	$cl_units->set_time("1750");
	$cl_units->set_att("150","1.045");
	$cl_units->set_def("400","1.045");
	$cl_units->set_defcav("150","1.045");
	$cl_units->set_defarcher("100","1.045");
	$cl_units->set_speed("720");
	$cl_units->set_booty("10");
	$cl_units->set_needed(array("barracks"=>"5","smith"=>"5"));
	$cl_units->set_recruit_in("barracks");
	$cl_units->set_specials(array());
	$cl_units->set_group("archer");
	$cl_units->set_col("A");
	$cl_units->set_attType("def");
	$cl_units->set_description("Com os seus olhos de águia e flechas afiadas os arqueiros são mortais à distancia. Eles podem apoia-lo em qualquer exército, quer estejas a atacar ou defender sua aldeia.");
}

$cl_units->add_unit("Espião","unit_spy");
$cl_units->set_woodprice("50");
$cl_units->set_stoneprice("50");
$cl_units->set_ironprice("20");
$cl_units->set_bhprice("2");
$cl_units->set_time("1250");
$cl_units->set_att("1","1.045");
$cl_units->set_def("10","1.045");
$cl_units->set_defcav("5","1.045");
$cl_units->set_defarcher("7","1.045");
$cl_units->set_speed("360");
$cl_units->set_booty("0");
$cl_units->set_needed(array("stable"=>1));
$cl_units->set_recruit_in("stable");
$cl_units->set_specials(array());
$cl_units->set_group("cav");
$cl_units->set_col("B");
$cl_units->set_attType("spy");
$cl_units->set_description("O ponto forte dos espiões não está na batalha. Eles são capazes de se esgueirarem dos seus inimigos pela calada da noite para espiar as suas aldeias. Quanto mais espiões tiver, mais detalhados serão os seus relatórios.");

$cl_units->add_unit("Cruzado","unit_light");
$cl_units->set_woodprice("125");
$cl_units->set_stoneprice("100");
$cl_units->set_ironprice("250");
$cl_units->set_bhprice("4");
$cl_units->set_time("2400");
$cl_units->set_att("900","1.045");
$cl_units->set_def("200","1.045");
$cl_units->set_defcav("300","1.045");
$cl_units->set_defarcher("300","1.045");
$cl_units->set_speed("390");
$cl_units->set_booty("80");
$cl_units->set_needed(array("stable"=>3));
$cl_units->set_recruit_in("stable");
$cl_units->set_specials(array());
$cl_units->set_group("cav");
$cl_units->set_col("B");
$cl_units->set_attType("off");
$cl_units->set_description("À distancia, os inimigos podem logo ver os impressionantes e radiantes estandartes dos cruzados. Estes guerreiros-da-luz são lutadores experientes que podem rápida e ferozmente cavalgar para um ataque. São indispensáveis se quiseres executar saques e ataques rapidamente.");

if($config['archers']){
	$cl_units->add_unit("Arqueiro a cavalo","unit_marcher");
	$cl_units->set_woodprice("250");
	$cl_units->set_stoneprice("100");
	$cl_units->set_ironprice("150 ");
	$cl_units->set_bhprice("5");
	$cl_units->set_time("1250");
	$cl_units->set_att("120","1.045");
	$cl_units->set_def("40","1.045");
	$cl_units->set_defcav("30","1.045");
	$cl_units->set_defarcher("50","1.045");
	$cl_units->set_speed("600");
	$cl_units->set_booty("50");
	$cl_units->set_needed(array("stable"=>"5" ));
	$cl_units->set_recruit_in("stable");
	$cl_units->set_specials(array(""));
	$cl_units->set_group("cav");
	$cl_units->set_col("B");
	$cl_units->set_description("Os Arqueiros a cavalo são especialmente úteis para derrotar Arqueiros inimigos escondidos atrás da Muralha.");
}

$cl_units->add_unit("Cavaleiro Negro","unit_heavy");
$cl_units->set_woodprice("200");
$cl_units->set_stoneprice("150");
$cl_units->set_ironprice("600");
$cl_units->set_bhprice("6");
$cl_units->set_time("3600");
$cl_units->set_att("600","1.045");
$cl_units->set_def("1500","1.045");
$cl_units->set_defcav("1000","1.045");
$cl_units->set_defarcher("1000","1.045");
$cl_units->set_speed("450");
$cl_units->set_booty("50");
$cl_units->set_needed(array("stable"=>"10","smith"=>"15"));
$cl_units->set_recruit_in("stable");
$cl_units->set_specials(array());
$cl_units->set_group("cav");
$cl_units->set_col("B");
$cl_units->set_attType("def");
$cl_units->set_description("Uma aura de poder sinistro envolve os cavaleiros negros. Eles invocam o medo e o terror naqueles que os avistam. Nunca ninguém os ouviu dizer uma palavra ou alguma vez os seus nomes foram ditos. Os cavaleiros negros não têm nenhuma fraqueza, mas o preço para os contratar é extremamente caro.");

$cl_units->add_unit("Aríete","unit_ram");
$cl_units->set_woodprice("300");
$cl_units->set_stoneprice("200");
$cl_units->set_ironprice("200");
$cl_units->set_bhprice("5");
$cl_units->set_time("1250");
$cl_units->set_att("100","1.045");
$cl_units->set_def("100","1.045");
$cl_units->set_defcav("200","1.045");
$cl_units->set_defarcher("20","1.045");
$cl_units->set_speed("1200");
$cl_units->set_booty("0");
$cl_units->set_needed(array("garage"=>"1"));
$cl_units->set_recruit_in("garage");
$cl_units->set_specials(array());
$cl_units->set_group("foot");
$cl_units->set_col("C");
$cl_units->set_attType("off");
$cl_units->set_description("Não existem muitas muralhas capazes de suportar o poder de 10 homens e da coroa de aço do aríete. Infelizmente o seu peso é um fardo e faz com que se mova muito lentamente.");

$cl_units->add_unit("Catapulta","unit_catapult");
$cl_units->set_woodprice("320");
$cl_units->set_stoneprice("400");
$cl_units->set_ironprice("100");
$cl_units->set_bhprice("8");
$cl_units->set_time("1250");
$cl_units->set_att("500","1.045");
$cl_units->set_def("400","1.045");
$cl_units->set_defcav("100","1.045");
$cl_units->set_defarcher("200","1.045");
$cl_units->set_speed("1440");
$cl_units->set_booty("0");
$cl_units->set_needed(array("garage"=>"2","smith"=>"12"));
$cl_units->set_recruit_in("garage");
$cl_units->set_specials(array());
$cl_units->set_group("foot");
$cl_units->set_col("C");
$cl_units->set_attType("undefined");
$cl_units->set_description("A Catapulta possui uma técnica mortal: as suas tiras de couro são capazes de catapultar as mais pesadas pedras sobre os seus inimigos. Também permite bombardear edifícios. No entanto, necessita de uma escolta, uma vez que obviamente não consegue defender-se sozinho.");

$cl_units->add_unit("Paladino","unit_knight");
$cl_units->set_woodprice("20");
$cl_units->set_stoneprice("20");
$cl_units->set_ironprice("40");
$cl_units->set_bhprice("10");
$cl_units->set_time("34424");
$cl_units->set_att("150","1.045");
$cl_units->set_def("250","1.045");
$cl_units->set_defcav("400","1.045");
$cl_units->set_defarcher("150","1.045");
$cl_units->set_speed("400");
$cl_units->set_booty("100");
$cl_units->set_needed(array());
$cl_units->set_recruit_in("statue");
$cl_units->set_specials(array("no_investigate"));
$cl_units->set_group("cav");
$cl_units->set_col("D");
$cl_units->set_attType("undefined");
$cl_units->set_description("O paladino protege a aldeia e seus aliados contra ataques de inimigos. Cada jogador pode possuir apenas um paladino.");

$cl_units->add_unit("Nobre","unit_snob");
if($config['ag_style'] == 2){
  $cl_units->set_woodprice("40000");
  $cl_units->set_stoneprice("50000");
  $cl_units->set_ironprice("50000");
}else{
  $cl_units->set_woodprice("28000");
  $cl_units->set_stoneprice("30000");
  $cl_units->set_ironprice("25000");
}
$cl_units->set_bhprice("100");
$cl_units->set_time("12500");
$cl_units->set_att("100","1.045");
$cl_units->set_def("300","1.045");
$cl_units->set_defcav("100","1.045");
$cl_units->set_defarcher("200","1.045");
$cl_units->set_speed("1800");
$cl_units->set_booty("0");
$cl_units->set_needed(array("main"=>"20","smith"=>"20","market"=>"10"));
$cl_units->set_recruit_in("snob");
$cl_units->set_specials(array("no_investigate"));
$cl_units->set_group("foot");
$cl_units->set_col("D");
$cl_units->set_attType("undefined");
$cl_units->set_description("Podes ouvir à distância som da fanfarra real a anunciar a chegada do Nobre que tomará conta dos assuntos da aldeia em teu nome. Como delegado de sua majestade pode convencer uma aldeia inteira a juntar-se ao teu reino.");
?>